[project]
name = "finetuningpractice"
version = "0.1.0"
description = "Fine-tuning practice with transformers and deep learning"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    # Core ML/Data Science
    "numpy>=2.3.3",
    "pandas>=2.3.3",
    "scikit-learn>=1.7.2",
    
]
